KEYWORDS = [
    'ai',
    'artificial intelligence',
    'gpt',
    'gpt-2',
    'gpt-3',
    'gpt-4',
    'llm',
    'large language model',
    'openai',
    'language model',
    'cursor ai',
    'chatgpt',
    'anthropic',
    'claude',
    'bard',
    'copilot',
    'google ai',
    'vertex ai',
    'gemini',
    'mistral',
    'llama',
    'llama 2',
    'llama 3',
    'meta ai',
    'alpa',
    'falcon',
    'stable diffusion',
    'midjourney',
    'dall-e',
    'dalle',
    'huggingface',
    'transformer',
    'prompt engineering',
    'prompt injection',
    'autogen',
    'langchain',
    'agentic',
    'agent',
    'autogpt',
    'babyagi',
    'chatbot',
    'machine learning',
    'deep learning',
    'neural network',
    'stablelm',
    'vicuna',
    'alpaca',
    'wizardlm',
    'chatsonic',
    'perplexity',
    'pi ai',
    'pi.ai',
    'replika',
    'jasper',
    'copy ai',
    'writesonic',
    'notion ai',
    'you.com',
    'bing ai',
    'bing chat',
    'microsoft ai',
    'cohere',
    'ai21',
    'jurassic',
    'ernie',
    'wenxin',
    'baidu ai',
    'alibaba ai',
    'sensechat',
    'sense ai',
    'deepmind',
    'alphafold',
    'alphago',
    'alphazero',
    'chatpdf',
    'chatdoc',
    'chatfile',
    'chatlaw',
    'chatglm',
    'glm',
    'qwen',
    'moonshot',
    'zero-shot',
    'few-shot',
    'finetune',
    'finetuning',
    'instruct',
    'instruction tuning',
    'self-attention',
    'attention mechanism',
    'diffusion model',
    'stable diffusion',
    'dreambooth',
    'controlnet',
    'sdxl',
    'sdxl turbo',
    'runwayml',
    'runway',
    'ai tool',
    'ai assistant',
    'ai model',
    'ai system',
    'ai-powered',
    'ai-driven',
    'ai-based',
    'ai-generated',
    'ai content',
    'ai art',
    'ai image',
    'ai text',
    'ai code',
    'ai writing',
    'ai chatbot',
    'ai search',
    'ai summary',
    'ai summarization',
    'ai translation',
    'ai transcription',
    'ai detection',
    'ai classifier',
    'ai generator',
    'ai completion',
    'ai prompt',
    'ai prompts',
    'ai workflow',
    'ai pipeline',
    'ai automation',
    'ai research',
    'ai ethics',
    'ai safety',
    'ai alignment',
    'ai explainability',
    'ai interpretability',
    'ai hallucination',
    'ai bias',
    'ai fairness',
    'ai regulation',
    'ai governance',
    'ai policy',
    'ai law',
    'ai compliance',
    'ai security',
    'ai privacy',
    'ai risk',
    'ai trust',
    'ai transparency',
    'ai monitoring',
    'ai evaluation',
    'ai benchmark',
    'ai leaderboard',
    'ai competition',
    'ai challenge',
    'ai hackathon',
    'ai conference',
    'ai workshop',
    'ai meetup',
    'ai community',
    'ai forum',
    'ai blog',
    'ai newsletter',
    'ai podcast',
    'ai video',
    'ai course',
    'ai tutorial',
    'ai book',
    'ai paper',
    'ai dataset',
    'ai corpus',
    'ai annotation',
    'ai labeling',
    'ai labeling tool',
    'ai annotation tool',
    'ai data',
    'ai training',
    'ai inference',
    'ai deployment',
    'ai serving',
    'ai api',
    'ai endpoint',
    'ai platform',
    'ai cloud',
    'ai infrastructure',
    'ai hardware',
    'ai chip',
    'ai accelerator',
    'ai cluster',
    'ai supercomputer',
    'ai lab',
    'ai startup',
    'ai company',
    'ai product',
    'ai service',
    'ai solution',
    'ai vendor',
    'ai provider',
    'ai consultant',
    'ai expert',
    'ai specialist',
    'ai engineer',
    'ai scientist',
    'ai researcher',
    'ai developer',
    'ai architect',
    'ai designer',
    'ai manager',
    'ai leader',
    'ai executive',
    'ai investor',
    'ai fund',
    'ai grant',
    'ai award',
    'ai prize',
    'ai patent',
    'ai license',
    'ai standard',
    'ai framework',
    'ai library',
    'ai toolkit',
    'ai package',
    'ai module',
    'ai script',
    'ai notebook',
    'ai repo',
    'ai github',
    'ai colab',
    'ai kaggle',
    'ai huggingface',
    'ai model hub',
    'ai zoo',
    'ai benchmark',
    'ai leaderboard',
    'ai evaluation',
    'ai test',
    'ai validation',
    'ai experiment',
    'ai ablation',
    'ai baseline',
    'ai metric',
    'ai score',
    'ai result',
    'ai output',
    'ai input',
    'ai feature',
    'ai label',
    'ai target',
    'ai prediction',
    'ai classification',
    'ai regression',
    'ai clustering',
    'ai generation',
    'ai synthesis',
    'ai simulation',
    'ai emulation',
    'ai optimization',
    'ai search',
    'ai planning',
    'ai reasoning',
    'ai logic',
    'ai knowledge',
    'ai memory',
    'ai attention',
    'ai perception',
    'ai vision',
    'ai speech',
    'ai audio',
    'ai text',
    'ai nlp',
    'ai cv',
    'ai rl',
    'ai robotics',
    'ai agent',
    'ai multi-agent',
    'ai swarm',
    'ai collective',
    'ai emergent',
    'ai general',
    'agi',
    'artificial general intelligence',
    'asi',
    'artificial superintelligence',
]

def get_keywords():
    return KEYWORDS 